[package]
name = "rusolver"
version = "0.1.0"
authors = ["Eduard Tolosa <edu4rdshl@protonmail.com>"]
edition = "2018"
description = "Fast DNS resolver written in Rust."
repository = "https://github.com/edu4rdshl/rusolver"
license = "GPL-3.0-or-later"
keywords = ["dns-resolution", "dns-resolver"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
futures = "0.3.5"
trust-dns-resolver = "0.19.5"
clap = "2.33.3"
rand = "0.7.3"
